// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.4
// source: calcservice.proto

package protofiles

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ? Enum for the operations
type Op int32

const (
	Op_DIVI Op = 0
	Op_MULT Op = 1
	Op_SUMA Op = 2
	Op_SUBT Op = 3
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "DIVI",
		1: "MULT",
		2: "SUMA",
		3: "SUBT",
	}
	Op_value = map[string]int32{
		"DIVI": 0,
		"MULT": 1,
		"SUMA": 2,
		"SUBT": 3,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_calcservice_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_calcservice_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_calcservice_proto_rawDescGZIP(), []int{0}
}

// ? The object with the desired operations
type OperationObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num1 int32 `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2 int32 `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
	Op   Op    `protobuf:"varint,3,opt,name=op,proto3,enum=protofiles.Op" json:"op,omitempty"`
}

func (x *OperationObj) Reset() {
	*x = OperationObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calcservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationObj) ProtoMessage() {}

func (x *OperationObj) ProtoReflect() protoreflect.Message {
	mi := &file_calcservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationObj.ProtoReflect.Descriptor instead.
func (*OperationObj) Descriptor() ([]byte, []int) {
	return file_calcservice_proto_rawDescGZIP(), []int{0}
}

func (x *OperationObj) GetNum1() int32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *OperationObj) GetNum2() int32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

func (x *OperationObj) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_DIVI
}

// ? The object for the result
type ResultObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResultObj) Reset() {
	*x = ResultObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calcservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultObj) ProtoMessage() {}

func (x *ResultObj) ProtoReflect() protoreflect.Message {
	mi := &file_calcservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultObj.ProtoReflect.Descriptor instead.
func (*ResultObj) Descriptor() ([]byte, []int) {
	return file_calcservice_proto_rawDescGZIP(), []int{1}
}

func (x *ResultObj) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ResultObj) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ? The List of result obj
type ResultObjList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultList []*ResultObj `protobuf:"bytes,1,rep,name=result_list,json=resultList,proto3" json:"result_list,omitempty"`
}

func (x *ResultObjList) Reset() {
	*x = ResultObjList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calcservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultObjList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultObjList) ProtoMessage() {}

func (x *ResultObjList) ProtoReflect() protoreflect.Message {
	mi := &file_calcservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultObjList.ProtoReflect.Descriptor instead.
func (*ResultObjList) Descriptor() ([]byte, []int) {
	return file_calcservice_proto_rawDescGZIP(), []int{2}
}

func (x *ResultObjList) GetResultList() []*ResultObj {
	if x != nil {
		return x.ResultList
	}
	return nil
}

var File_calcservice_proto protoreflect.FileDescriptor

var file_calcservice_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x6c, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22,
	0x56, 0x0a, 0x0c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e,
	0x75, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x12, 0x1e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x35, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x4f, 0x62, 0x6a, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x47,
	0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x62, 0x6a, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x36, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x62, 0x6a, 0x52, 0x0a, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x2a, 0x2c, 0x0a, 0x02, 0x4f, 0x70, 0x12, 0x08, 0x0a,
	0x04, 0x44, 0x49, 0x56, 0x49, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x55, 0x4c, 0x54, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x55, 0x4d, 0x41, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x53,
	0x55, 0x42, 0x54, 0x10, 0x03, 0x32, 0x96, 0x01, 0x0a, 0x06, 0x44, 0x6f, 0x4d, 0x61, 0x74, 0x68,
	0x12, 0x40, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x63, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4f, 0x62, 0x6a,
	0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0f, 0x43, 0x61, 0x6c, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x1a,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x4f, 0x62, 0x6a, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x42, 0x11,
	0x5a, 0x0f, 0x63, 0x61, 0x6c, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calcservice_proto_rawDescOnce sync.Once
	file_calcservice_proto_rawDescData = file_calcservice_proto_rawDesc
)

func file_calcservice_proto_rawDescGZIP() []byte {
	file_calcservice_proto_rawDescOnce.Do(func() {
		file_calcservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_calcservice_proto_rawDescData)
	})
	return file_calcservice_proto_rawDescData
}

var file_calcservice_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_calcservice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_calcservice_proto_goTypes = []interface{}{
	(Op)(0),               // 0: protofiles.Op
	(*OperationObj)(nil),  // 1: protofiles.OperationObj
	(*ResultObj)(nil),     // 2: protofiles.ResultObj
	(*ResultObjList)(nil), // 3: protofiles.ResultObjList
}
var file_calcservice_proto_depIdxs = []int32{
	0, // 0: protofiles.OperationObj.op:type_name -> protofiles.Op
	2, // 1: protofiles.ResultObjList.result_list:type_name -> protofiles.ResultObj
	1, // 2: protofiles.DoMath.CalcNumbers:input_type -> protofiles.OperationObj
	1, // 3: protofiles.DoMath.CalcListNumbers:input_type -> protofiles.OperationObj
	2, // 4: protofiles.DoMath.CalcNumbers:output_type -> protofiles.ResultObj
	3, // 5: protofiles.DoMath.CalcListNumbers:output_type -> protofiles.ResultObjList
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_calcservice_proto_init() }
func file_calcservice_proto_init() {
	if File_calcservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calcservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calcservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calcservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultObjList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calcservice_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calcservice_proto_goTypes,
		DependencyIndexes: file_calcservice_proto_depIdxs,
		EnumInfos:         file_calcservice_proto_enumTypes,
		MessageInfos:      file_calcservice_proto_msgTypes,
	}.Build()
	File_calcservice_proto = out.File
	file_calcservice_proto_rawDesc = nil
	file_calcservice_proto_goTypes = nil
	file_calcservice_proto_depIdxs = nil
}
